### ISSUE TITLE
Last step in tutorial ended up in a back-only loop

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/Spoke#649] opened 2019-05-15 16:17 UTC
I'm not sure what I did wrong, but once I got to the final step of the tutorial, I was expecting to see a close/finish button but instead got to a summary of the letter character things with a BACK button and then the previous page would just say NEXT and they'd just bounce back/forth until I hit ESC to cancel out.

Sorry if this is vague; if it's not clear where I got lost, lmk and I'll try it again and take some screenshots!

**Comment by robertlong** [comment] 2019-05-15 16:43
@larsbergstrom are you talking about this page?
![Screen Shot 2019-05-15 at 9 41 09 AM](https://user-images.githubusercontent.com/1753624/57793191-9a577a00-76f5-11e9-90f9-e5e194b9aa0b.png)

I'm not sure what you mean by `letter character things`. I also don't know what you cancel out by hitting the ESC key. A little more detail would be great!

**Comment by larsbergstrom** [comment] 2019-05-15 16:52
Sorry for being vague! It was this one:

<img width="1422" alt="Screen Shot 2019-05-15 at 11 50 46 AM" src="https://user-images.githubusercontent.com/475847/57793758-b49a5380-7707-11e9-8bdc-addf40031420.png">

I suspect the issue is that it really wanted me to click on the shadows, now that I read it more closely :-) I kept hitting next to "skip" past it but then I'd get the "back" button that would return to this dialog from the one above.

**Comment by robertlong** [comment] 2019-05-15 17:49
It's actually the other way around 😅 The save dialog really wants you to save the project and I've disabled the next button on that dialog. You can skip right past enabling the cast shadow checkbox popover.

I guess this needs some work. We're discussing it right now in Discord, so more to come.

**Comment by robertlong** [comment] 2021-01-12 19:10
I think this is a duplicate of https://github.com/mozilla/Spoke/issues/510

**Closed by robertlong** 2021-01-12 19:10 UTC
Labels: P2, bug, needs repro
