### ISSUE TITLE
Persitant Thumbnail Camera Position

### ISSUE THREAD

**Issue by emclaren** [mozilla/Spoke#928] opened 2020-03-05 23:32 UTC
*Enhancement Request*

When I build scenes in Hubs, it would be nice if the position of the thumbnail image viewpoint didn't keep moving each time I republish the scene. I would like to be able to set it, and have the location stay persistent until I choose to set a new one. 

It works fine now, but sometimes I go to make a quick change and then the thumbnail gets redone from the wrong place so I have to go back and re-upload the scene to get the right viewpoint again. 

Not pressing, but something I think of quite often when building scenes.

**Comment by robertlong** [comment] 2020-03-06 20:47
Thanks for filing this! It's a duplicate of #284 though so I'm going to close and we can continue discussion over there.

**Closed by robertlong** 2020-03-06 20:47 UTC
