### ISSUE TITLE
Featured scenes do not appear on the “New Project” page

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/Spoke#1082] opened 2021-01-22 12:29 UTC
**[Affected Versions]:**
- Firefox Release 84.0.2

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- A Hubs Cloud Instance is set up.
- Make sure to have some scenes imported, created and featured.
- Spoke is opened from a Hubs Cloud instance.

**[Steps to reproduce]:**
1. Click the "New Project" button.
2. Click the "Featured" button.
3. Observe the list.

**[Expected results]:**
- The list of featured projects is displayed.

**[Actual results]:**
- The list of featured projects is NOT displayed.

**[Notes]:**
- Attached a screen recording of the issue below
![featured projects](https://user-images.githubusercontent.com/51400741/105490906-2c32cb00-5cbe-11eb-88c4-e18b359ee657.gif)

**Comment by misslivirose** [comment] 2021-01-22 13:46
This is expected behavior. Featured scenes are different from Spoke project templates. Project templates are added separately from scene files in an instance.

**Comment by Softvision-GeluHaiduc** [comment] 2021-01-25 07:04
@misslivirose Could you please give me some more details on how to add project templates to the Hubs Cloud instance?

**Comment by misslivirose** [comment] 2021-01-25 14:29
As far as I understand it, changing the default projects in the scene editor requires deploying a custom deployment of Spoke to Hubs Cloud (the projects are in the /src/assets/templates directory). While I think some people have done it, I don't think we have an endorsed path for doing custom Spoke deployments that is well-tooled out yet, so I don't think it's in-scope right now for Hubs Cloud testing. (@johnshaughnessy, thoughts?)

**Comment by johnshaughnessy** [comment] 2021-01-25 17:27
I think the projects used to be pulled from `/src/assets/templates` as you said, but it looks like we changed that to pull `"featured-remixable"` scenes from `reticulum`:
https://github.com/mozilla/Spoke/blob/de2209b8f05e9ec73a6f0d3b59865a0ef6c310a9/src/ui/projects/CreateProjectPage.js#L115-L120

I can't tell if the templates in the repo are still used or if [maybe they should be removed](https://github.com/mozilla/Spoke/pull/1084).

There does not seem to be a convenient way to find these `featured-remixable` scene [listings?] in the admin panel, but I think to add a new one you would find a scene, feature it, and set to be remixable. I don't know the history here. Maybe @robertlong can add some details?

**Comment by misslivirose** [comment] 2021-01-25 17:42
Huh. TIL - sorry for my original mistake in thinking that this was expected behavior. This was added when I was out on leave last year. 

Saw that this was apparently the intended behavior in https://github.com/mozilla/Spoke/pull/865, but it seems to have not been working for some time because there would otherwise be far more projects on hubs.mozilla.com/spoke, wouldn't there? 

For example, the Holiday scenes and the Mozilla Commons are both 'featured' and have the ability to be remixed on HMC but neither of them are templates either.

IMO, I question that these should be the same set of scenes a bit given the possibility that the published scene is fine but the Spoke file has some hidden stuff we might want to check out before featuring, but it may be fine.

**Comment by robertlong** [comment] 2021-01-25 17:47
I don't really have anything to add. Yeah, we use the `featured-remixable` tag to feature scenes in Spoke. I think that's probably the right way to do this. It'd be nice if it were more discoverable in the admin panel though.

**Comment by misslivirose** [comment] 2021-01-25 17:49
@robertlong - thank you for clarifying the tag - so we have 'featured' and 'remixable' separately, and then 'featured-remixable' for scenes to appear as default Spoke projects?

**Comment by robertlong** [comment] 2021-01-26 22:21
@misslivirose yup, that's correct. Although I think `remixable` is not a tag, but a boolean property of a scene/scene listing. A bit confusing for sure.

**Comment by robertlong** [comment] 2021-03-22 17:33
I'm going to close this issue. You need to use the `featured-remixable` tag in Hubs Cloud to have a scene visible in Spoke's new project page.

**Closed by robertlong** 2021-03-22 17:33 UTC
Labels: HC-January-Release, [QA]:Normal issue
