### ISSUE TITLE
Snapping can become inverted

### ISSUE THREAD

**Issue by netpro2k** [mozilla/Spoke#559] opened 2019-04-25 22:52 UTC
Not 100% sure how I did it but managed to get snapping to become inverted. It was resolved after tapping the ctrl key so I assume whatever internal state tracks the ctrl key was stuck on.

**Comment by robertlong** [comment] 2019-05-07 18:42
I haven't been able to reproduce this. I'm going to move this out of priority for now.

**Comment by robertlong** [comment] 2019-10-01 16:54
I haven't seen this in a while so I'm going to close this, the Spoke controls were cleaned up since this issue was reported, perhaps we fixed the issue.

**Closed by robertlong** 2019-10-01 16:54 UTC
Labels: bug, needs repro
