### ISSUE TITLE
The scene fail to load

### ISSUE THREAD

**Issue by Hong0306** [mozilla/Spoke#1265] opened 2022-11-22 14:05 UTC
Hi there
Whenever I try to create a room after I publish my scenes to hub, I get a message like this.
'The scene failed to load.'
though everything just worked at about 5 hours ago.
Can I get some help?

**Comment by matthewbcool** [comment] 2022-11-22 14:50
Could you please open and fill out a complete bug report (steps to reproduce, browser, ect.)? There is not enough information to act on. Closing and unable to reproduce. 
https://github.com/mozilla/Spoke/issues/new?assignees=&labels=&template=bug_report.md&title=

**Closed by matthewbcool** 2022-11-22 14:50 UTC
