### ISSUE TITLE
Hubs Cloud is offline

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/Spoke#1128] opened 2021-04-07 11:00 UTC
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline

**Comment by johnshaughnessy** [comment] 2021-04-07 13:24
Duplicate of https://github.com/mozilla/hubs/issues/4097

**Closed by johnshaughnessy** 2021-04-07 13:24 UTC
