### ISSUE TITLE
e is not iterable

### ISSUE THREAD

**Issue by MichaelaArmani** [mozilla/Spoke#1210] opened 2022-01-26 17:52 UTC
<img width="1423" alt="Schermafbeelding 2022-01-26 om 18 49 47" src="https://user-images.githubusercontent.com/98482963/151218691-cb5e8922-da0e-43fe-b996-a5328ac0a20a.png">

Can someone help me with this problem? I'm trying to export this file but I always get this message... and I have no idea where it comes from

**Comment by Exairnous** [comment] 2022-01-26 22:57
This is a long-standing bug, basically it means that you have no 3d models in the scene and so won't publish.  The workaround is to add some type of 3d model to your scene e.g. a ground plane (but if you don't want a ground plane I would expect you could also upload a real low poly model, or even a single vertex, and scale it to 0 or set it to be not visible and that should also work).
See https://github.com/mozilla/Spoke/issues/1137 for more details.

**Comment by MichaelaArmani** [comment] 2022-01-27 21:18
Thankyou so much for your help!! This was indeed the problem and I have now been able to export it.

**Comment by Exairnous** [comment] 2022-01-27 21:47
You're welcome!  Glad I could help :)

**Comment by matthewbcool** [comment] 2022-03-14 21:26
closing duplicate of https://github.com/mozilla/Spoke/issues/1137

**Closed by matthewbcool** 2022-03-14 21:26 UTC
